default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: villages_nourriciers_development

test:
  <<: *default
  database: villages_nourriciers_test

production:
  <<: *default
  database: citizen_platform_production
